############# English navigation ##############

# main menu
[[main]]
name = "About"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/pages"
weight = 2

[[main]]
name = "Tags"
pageRef = "/tags"
weight = 3

# footer menu
# [[footer]]
# name = "About"
# pageRef = "/about"
# weight = 1
#
# [[footer]]
# name = "Elements"
# pageRef = "/elements"
# weight = 2
#
# [[footer]]
# name = "Privacy Policy"
# pageRef = "/privacy-policy"
# weight = 3
